import type { Config } from 'tailwindcss';

export default {
  darkMode: 'class',
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      colors: {
        outline: '#75777c',
        'surface-dim': '#d3daea',
        'surface-container-lowest': '#ffffff',
        'on-primary-fixed-variant': '#3d4756',
        'on-secondary-container': '#682c00',
        'on-tertiary-fixed': '#191c1d',
        'surface-tint': '#555f6f',
        surface: '#f9f9ff',
        'surface-container-high': '#e2e8f8',
        'on-secondary-fixed': '#331200',
        'inverse-surface': '#2a313d',
        'on-secondary': '#ffffff',
        'on-error-container': '#93000a',
        'on-primary-container': '#8690a1',
        'on-tertiary': '#ffffff',
        'on-secondary-fixed-variant': '#763300',
        'inverse-primary': '#bdc7d9',
        'primary-fixed-dim': '#bdc7d9',
        'outline-variant': '#c5c6cc',
        'on-tertiary-fixed-variant': '#454748',
        'on-primary-fixed': '#121c2a',
        'secondary-fixed': '#ffdbca',
        'secondary-container': '#fd8a42',
        'primary-fixed': '#d9e3f6',
        'on-error': '#ffffff',
        'on-background': '#151c27',
        primary: '#0a1422',
        'tertiary-container': '#26292a',
        'surface-container': '#e7eefe',
        tertiary: '#121516',
        'surface-container-highest': '#dce2f3',
        background: '#f9f9ff',
        'on-surface-variant': '#44474c',
        secondary: '#9b4500',
        'surface-bright': '#f9f9ff',
        'primary-container': '#1f2937',
        'error-container': '#ffdad6',
        'on-primary': '#ffffff',
        'inverse-on-surface': '#ebf1ff',
        'on-tertiary-container': '#8e9091',
        'tertiary-fixed-dim': '#c5c7c8',
        'surface-variant': '#dce2f3',
        error: '#ba1a1a',
        'on-surface': '#151c27',
        'secondary-fixed-dim': '#ffb68e',
        'tertiary-fixed': '#e1e3e4',
        'surface-container-low': '#f0f3ff',
        'brand-accent': '#8B5E3C',
      },
      spacing: {
        'margin-mobile': '16px',
        'container-max': '1280px',
        'section-gap': '120px',
        'margin-desktop': '64px',
        gutter: '24px',
        base: '8px',
      },
      fontFamily: {
        sans: ['Inter', 'system-ui', 'sans-serif'],
        serif: ['"Playfair Display"', 'Georgia', 'serif'],
      },
      fontSize: {
        'headline-md': ['24px', { lineHeight: '1.3', fontWeight: '600' }],
        'headline-lg': [
          '32px',
          { lineHeight: '1.2', letterSpacing: '-0.01em', fontWeight: '700' },
        ],
        'body-lg': ['18px', { lineHeight: '1.6', fontWeight: '400' }],
        'label-caps': ['12px', { lineHeight: '1', letterSpacing: '0.05em', fontWeight: '700' }],
        'headline-xl': [
          '48px',
          { lineHeight: '1.1', letterSpacing: '-0.02em', fontWeight: '800' },
        ],
        'body-md': ['16px', { lineHeight: '1.6', fontWeight: '400' }],
      },
    },
  },
  plugins: [],
} satisfies Config;
